language: python

sudo: false

env:
  - TOXENV=pep8
  - TOXENV=py3pep8
  - TOXENV=docs
  - TOXENV=packaging
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy

install: pip install tox

script: tox
